<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_contact us_icon-md icon-close dialog-clos_a06fe5</name>
   <tag></tag>
   <elementGuidId>5f684814-a4fd-433f-a03d-c8b9ecabf20b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.icon-md.icon-close.dialog-close-button.js-close-window</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chrome-container']/div[3]/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-md icon-close dialog-close-button js-close-window</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chrome-container&quot;)/div[@class=&quot;window-overlay&quot;]/div[@class=&quot;window&quot;]/div[@class=&quot;window-wrapper js-tab-parent&quot;]/a[@class=&quot;icon-md icon-close dialog-close-button js-close-window&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chrome-container']/div[3]/div/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[68]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
