<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jump to recent and starred boards, or _de8be4</name>
   <tag></tag>
   <elementGuidId>8044e32d-15f4-4d1a-a5fa-0ab540a8d4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.SETnvPbUKHW-cx._3XZPT267JcxN7w._1hy9FIxNNwKdWB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div[4]/button[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lana Hameda (lanahameda2)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SETnvPbUKHW-cx _3XZPT267JcxN7w _1hy9FIxNNwKdWB</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;_1IG3vG_3YjVvUJ&quot;]/button[@class=&quot;_2Twwgx1RZOAQRy js-open-header-member-menu a0_VCPbYTNd2WP _3TTqkG5muwOzqZ ZOUktZwsING7-0 _1Tu9wiuW4Te8Rx&quot;]/div[@class=&quot;_2LKdO6O3n25FhC&quot;]/span[@class=&quot;SETnvPbUKHW-cx _3XZPT267JcxN7w _1hy9FIxNNwKdWB&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[4]/button[3]/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/div/span</value>
   </webElementXpaths>
</WebElementEntity>
